apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: repl
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  externalClusters:
  - name: src
    connectionParameters:
      host: src-rw
      user: postgres
      dbname: postgres
      sslmode: disable
  bootstrap:
    pg_basebackup:
      source: src
  storage:
    size: 1Gi
